SESSION_ID: kord_ai-Ko1wg1y9VLwQY6fw
OWNER_NUMBER: 2349160574996
WORKTYPE: private
PREFIX: . or [.!] 
TIMEZONE: Africa/Lagos
OWNER_NAME: savage
BOT_NAME: savage
RENDER_API_KEY: rnd_PJ30pR2EwEWpeCbSqMmTWR8CP2fJ