SESSION_ID: kord_ai-Ko1wg1y9VLwQY6fw
OWNER_NUMBER: Your WhatsApp number with country code (e.g., 23490xxxxxxx)
WORKTYPE: public or private
PREFIX: . or [.!] 
TIMEZONE: Africa/Lagos
OWNER_NAME: savage
BOT_NAME: savage
RENDER_API_KEY: rnd_PJ30pR2EwEWpeCbSqMmTWR8CP2fJ